# Generated by Django 5.2.3 on 2025-07-08 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE_USER', 'Création user'), ('UPLOAD_DOCUMENT', 'Téléversement document'), ('DELETE_DOCUMENT', 'Suppression document'), ('VIEW_DOCUMENT', 'Consultation document')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
