# Generated by Django 5.2.3 on 2025-07-08 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('niveau_urgence', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='notes_pieces_jointes/')),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note Flash',
                'verbose_name_plural': 'Notes Flash',
                'ordering': ['-niveau_urgence', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NoteReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions_notes', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='notes.noteinterne')),
            ],
            options={
                'unique_together': {('note', 'destinataire')},
            },
        ),
        migrations.AddField(
            model_name='noteinterne',
            name='destinataires',
            field=models.ManyToManyField(related_name='notes_recues', through='notes.NoteReception', to=settings.AUTH_USER_MODEL),
        ),
    ]
