# Generated by Django 5.2.3 on 2025-07-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notereception',
            name='est_archivee',
            field=models.BooleanField(default=False),
        ),
    ]
