# Generated by Django 5.2.3 on 2025-07-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notereception_est_archivee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notereception',
            old_name='lue',
            new_name='est_lue',
        ),
    ]
