# Generated by Django 5.2.3 on 2025-07-10 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priorite', models.IntegerField(default=3)),
                ('jour_prevu', models.CharField(blank=True, choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi')], max_length=3, null=True)),
                ('prevue_aujourdhui', models.BooleanField(default=False)),
                ('est_terminee', models.BooleanField(default=False)),
                ('heure_debut', models.DateTimeField(blank=True, null=True)),
                ('heure_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_total', models.DurationField(default=0)),
                ('commentaire_rh', models.TextField(blank=True)),
                ('fiche_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='todo.ficheposte')),
            ],
        ),
    ]
