# Generated by Django 5.2.3 on 2025-07-11 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('is_modele', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('jour_prevu', models.PositiveIntegerField(blank=True, null=True)),
                ('commentaire_rh', models.TextField(blank=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('pause_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duree_total', models.DurationField(blank=True, null=True)),
                ('fiche_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='todo.ficheposte')),
            ],
        ),
        migrations.CreateModel(
            name='TacheSelectionnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_selection', models.DateField()),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.tache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
