# Generated by Django 5.2.3 on 2025-07-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_planifiee',
            field=models.DateField(blank=True, null=True),
        ),
    ]
