# Generated by Django 5.2.3 on 2025-07-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_suivitache'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacheselectionnee',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacheselectionnee',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tacheselectionnee',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tacheselectionnee',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tacheselectionnee',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
