# Generated by Django 5.2.3 on 2025-07-11 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tache_date_planifiee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheposte',
            name='is_modele',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ficheposte',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL),
        ),
    ]
