# Generated by Django 5.2.3 on 2025-07-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_tacheselectionnee_end_time_tacheselectionnee_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacheselectionnee',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
