# Generated by Django 5.2.3 on 2025-07-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_ficheposte_is_modele_alter_ficheposte_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='duree_total',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
