# Generated by Django 5.2.3 on 2025-07-13 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_pausetache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pausetache',
            name='tache',
        ),
        migrations.RemoveField(
            model_name='suivitache',
            name='tache',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='duree_total',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='pause_time',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='start_time',
        ),
        migrations.AddField(
            model_name='pausetache',
            name='tache_selectionnee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='todo.tacheselectionnee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suivitache',
            name='tache_selectionnee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='todo.tacheselectionnee'),
            preserve_default=False,
        ),
    ]
