# Generated by Django 5.2.3 on 2025-07-13 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_pausetache_tache_remove_suivitache_tache_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivitache',
            name='tache_selectionnee',
        ),
        migrations.AddField(
            model_name='suivitache',
            name='tache',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='todo.tache'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='duree_total',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tache',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tache',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tache',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PauseTache',
        ),
    ]
