# Generated by Django 5.2.3 on 2025-07-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_suivitache_tache_selectionnee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='duree_total',
            new_name='duree_brute',
        ),
    ]
