# Generated by Django 5.2.3 on 2025-07-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_rename_duree_total_tache_duree_brute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='pause_time',
        ),
        migrations.RemoveField(
            model_name='tacheselectionnee',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='tacheselectionnee',
            name='pause_time',
        ),
    ]
