# Generated by Django 5.2.3 on 2025-07-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_remove_tache_is_paused_remove_tache_pause_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tache',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacheselectionnee',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tacheselectionnee',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
