# Generated by Django 5.2.3 on 2025-07-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_tache_is_paused_tache_pause_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='duree_brute',
            new_name='duree_total',
        ),
    ]
