# Generated by Django 5.2.3 on 2025-07-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_rename_duree_brute_tache_duree_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='duree_total',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='pause_time',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='start_time',
        ),
    ]
