# Generated by Django 5.2.3 on 2025-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_remove_tache_duree_total_remove_tache_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacheselectionnee',
            name='commentaire_employe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacheselectionnee',
            name='commentaire_rh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
