# Generated by Django 5.2.3 on 2025-07-07 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('cv', 'CV'), ('motivation', 'Lettre de motivation'), ('fiche_suivi', 'Fiche de suivi terrain'), ('admin', 'Document administratif'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('visibilite', models.CharField(choices=[('admin', 'Administrateur uniquement'), ('rh', 'RH uniquement'), ('employe', 'Employés'), ('stagiaire', 'Stagiaires'), ('temporaire', 'Accès temporaire')], default='rh', max_length=20)),
                ('date_expiration_acces', models.DateField(blank=True, null=True)),
                ('affectations', models.ManyToManyField(blank=True, related_name='documents_attribues', to=settings.AUTH_USER_MODEL)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
