# Generated by Django 5.2.3 on 2025-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='visibilite',
            field=models.CharField(choices=[('admin', 'Administrateur uniquement'), ('rh', 'RH uniquement'), ('employe', 'Employés'), ('stagiaire', 'Stagiaires'), ('temporaire', 'Accès temporaire'), ('prive', 'Privé (auteur uniquement)')], default='rh', max_length=20),
        ),
    ]
