# Generated by Django 5.2.3 on 2025-07-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_visibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='visibilite',
            field=models.CharField(choices=[('admin', 'Administrateur uniquement'), ('rh', 'RH uniquement'), ('employe', 'Employés'), ('stagiaire', 'Tout le monde'), ('temporaire', 'Accès temporaire'), ('prive', 'Privé (auteur uniquement)')], default='rh', max_length=20),
        ),
    ]
