# Generated by Django 5.2.3 on 2025-07-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_visibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
