# Generated by Django 5.2.3 on 2025-07-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('cv', 'CV'), ('fiche_suivi', 'Fiche de suivi terrain'), ('admin', 'Document administratif'), ('grille', 'Grille Entretien'), ('contact', 'Liste contact'), ('candidature', 'Candidature Physique'), ('personnel', 'Suivi du personnel'), ('contrat', 'Contrat de travail'), ('dossier_agent', 'Dossier des agents'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
