# Generated by Django 5.2.3 on 2025-07-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_end_date'),
        ('todo', '0004_alter_tache_duree_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fiche_poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='todo.ficheposte'),
        ),
    ]
